### ISSUE TITLE
Problem with Schema that contains an Array of Objects

### ISSUE THREAD

**Issue by ziedmahdi** [pouya-eghbali/meteor-autoform#10]
Consider the following Schema:
```js
{
    clients: {
        type: Array
    },
    'clients.$': {
        type: Object
    },
    'clients.$.name': {
        type: String
    }
}
```

The global Blaze helper `afFieldNames` through an error as `AutoForm.findAttribute('fields')` returns: `['clients', false]`. As Boolean values do not have the `slice` method `field.slice` fails.

**Comment by pouya-eghbali** [comment]
Thanks for the PR!
