### ISSUE TITLE
Remove underscore

### ISSUE THREAD

**Issue by jankapunkt** [pouya-eghbali/meteor-autoform#2]
As discussed in the community packages forums, we should remove these utility package dependency.

**Comment by pouya-eghbali** [comment]
Task list:

- [X] `_.has` replace with `item in object`
- [X] `_.clone` replaced with `{ ...object }`
- [X] `_.extend` replaced with `{ ...a, ...b }` or `Object.assign(a, b)`
- [X] `_.filter` replaced with `array.filter`
- [X] `_.contains` replaced with `array.includes`
- [X] `_.isArray` replaced with `Array.isArray`
- [x] `_.keys` replaced with `Object.keys`
- [x] `_.unique` replaced with `[...new Set(array)]`
- [x] `_.compact` replaced with `array.filter(Boolean)`
- [x] `_.any` replaced with `array.some`
- [x] `_.map` replaced with `Object.entries(object).map`, `Object.values(object).map` or `array.map`
- [x] `_.throttle` replaced with [1]
- [x] `_.where` replaced with `Object.values(object).filter`
- [x] `_.reject` replaced with `array.filter`
- [x] `_.without` replaced with `array.filter` and `!array.includes`
- [x] `_.find` replaced with `array.find`
- [x] `_.last` replaced with `array.pop()`
- [x] `_.intersection` replaced with `array.filter` and `array.includes`
- [x] `_.isEmpty` replaced with `!Object.keys(object).length`
- [x] `_.difference` replaced with `Object.values(object).filter`
- [x] `_.isString` replaced with `'string' === typeof x`
- [x] `_.once` replaced with [2]
- [x] `_.isObject` replaced with [3]
- [x] `_.isFunction` replaced with [4]
- [x] `_.pick` replaced with ES6 destructuring 
- [x] `_.omit` replaced with ES6 destructuring
- [x] `_.all` replaced with `array.every`
- [x] `_.each` replaced with `Object.entries(object).forEach`, `Object.keys(object).forEach` or `array.forEach`

[1] throttle function
```javascript
function throttle(fn, limit) {
  let timeout
  return function (...args) {
    clearTimeout(timeout)
    timeout = setTimeout(function () {
      fn(...args)
    }, limit)
  }
}
```

[2] once implementation
```javascript
const fnOnce = () => {
  let alreadyRan = false
  return d => {
    if (alreadyRan) return
    alreadyRan = true
    return fn(d)
  }
}
```

[3] isObject

```javascript
export const isObject = obj => toString.call(obj) == '[object Object]' || Array.isArray(obj) || isFunction(obj)
```

[4] isFunction

```javascript
export const isFunction = obj => toString.call(obj) == '[object Function]'
```

**Comment by jankapunkt** [comment]
I could implement some of them. Do you need support on any of them?

**Comment by pouya-eghbali** [comment]
Some of them have an obvious alternative, some of them don't. For example I don't know what's the best way to do `_.isFunction`, should I do `x instanceof Function`? Should I do `"function" == typeof x`? For `_.isObject` it's even more complicated. Should we replace them by the exact underscore definitions?

**Comment by jankapunkt** [comment]
I think it depends on how "complete" our cases need these Functions to be. I have a gist with very close completeness: https://gist.github.com/jankapunkt/e43405ab19fd939ff058be1e9d4c177e

But this may be total overkill for many cases. Often Objects that are not a subclass of Object (like Array, String etc.) have the constructor `[Object]` while Array for example has the constructor name `[object Array]` (which is used via `Array.isArray`) so for simple checks this may be sufficient for 99% of the cases.

Using `instanceof` traverses the whole prototype chain and slows down things a lot. Maybe the most performant appraoch is to define the use cases, write some tests with most (better: all) occurring inputs and find the most minimal solution (like using 'function' === typeof x`)

**Comment by pouya-eghbali** [comment]
@jankapunkt https://gist.github.com/jankapunkt/e43405ab19fd939ff058be1e9d4c177e breaks autoform.

**Comment by pouya-eghbali** [comment]
I guess that's all of them!

**Comment by pouya-eghbali** [comment]
Ok, we don't depend on underscore anymore.

**Comment by pouya-eghbali** [comment]
Going to close this, this is done and if it causes any issues it should be followed in a new thread.
